#!/bin/bash

set -e

# config
BUILD_DIR="build"
BINARY_NAME="dosing-pump-server"
SERVER_IP="192.168.178.101"
REMOTE_DIR=/home/dosing-pump

# build stuff
mkdir -p $BUILD_DIR
env GOOS=linux GOARCH=arm GOARM=5 go build -o $BUILD_DIR/$BINARY_NAME cmd/main/main.go

# deploy stuff
scp $BUILD_DIR/dosing-pump-server dosing-pump@$SERVER_IP:$REMOTE_DIR/$BINARY_NAME
